"""insert_test_data

Revision ID: a85548e5b3f3
Revises: 667e65fcc8e2
Create Date: 2025-10-02 16:18:47.789502

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
from sqlalchemy import table, column, Integer, String, DateTime, Boolean

# revision identifiers, used by Alembic.
revision: str = 'a85548e5b3f3'
down_revision: Union[str, Sequence[str], None] = '667e65fcc8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    resource_types = table(
        'resource_types',
        column('id', Integer),
        column('name', String),
        column('description', String),
        column('created_at', DateTime),
        column('updated_at', DateTime)
    )

    user_roles = table(
        'user_roles',
        column('id', Integer),
        column('name', String),
        column('description', String),
        column('created_at', DateTime),
        column('updated_at', DateTime)
    )

    permissions = table(
        'permissions',
        column('id', Integer),
        column('name', String),
        column('description', String),
        column('resource_type_id', Integer),
        column('action', String),
        column('created_at', DateTime),
        column('updated_at', DateTime)
    )

    role_permissions_table = table(
        'role_permissions',
        column('role_id', Integer),
        column('permission_id', Integer),
        column('created_at', DateTime),
        column('updated_at', DateTime)
    )

    users = table(
        'users',
        column('id', Integer),
        column('name', String),
        column('email', String),
        column('hashed_password', String),
        column('is_active', Boolean),
        column('role_id', Integer),
        column('created_at', DateTime),
        column('updated_at', DateTime)
    )

    current_time = datetime.now()

    op.bulk_insert(resource_types, [
        {'id': 1, 'name': 'user', 'description': 'System users', 'created_at': current_time,
         'updated_at': current_time},
        {'id': 2, 'name': 'product', 'description': 'Products in catalog', 'created_at': current_time,
         'updated_at': current_time},
        {'id': 3, 'name': 'order', 'description': 'Customer orders', 'created_at': current_time,
         'updated_at': current_time},
        {'id': 4, 'name': 'category', 'description': 'Product categories', 'created_at': current_time,
         'updated_at': current_time},
    ])

    op.bulk_insert(user_roles, [
        {'id': 1, 'name': 'admin', 'description': 'Administrator with full access', 'created_at': current_time,
         'updated_at': current_time},
        {'id': 2, 'name': 'manager', 'description': 'Manager with limited admin access', 'created_at': current_time,
         'updated_at': current_time},
        {'id': 3, 'name': 'user', 'description': 'Regular user with basic access', 'created_at': current_time,
         'updated_at': current_time},
    ])

    op.bulk_insert(permissions, [
        # Users (resource_type_id=1)
        {'id': 1, 'name': 'user_create', 'description': 'Create users', 'resource_type_id': 1, 'action': 'create',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 2, 'name': 'user_read', 'description': 'Read users', 'resource_type_id': 1, 'action': 'read',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 3, 'name': 'user_update', 'description': 'Update users', 'resource_type_id': 1, 'action': 'update',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 4, 'name': 'user_delete', 'description': 'Delete users', 'resource_type_id': 1, 'action': 'delete',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 5, 'name': 'user_manage', 'description': 'Manage users', 'resource_type_id': 1, 'action': 'manage',
         'created_at': current_time, 'updated_at': current_time},

        # Products (resource_type_id=2)
        {'id': 6, 'name': 'product_create', 'description': 'Create products', 'resource_type_id': 2, 'action': 'create',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 7, 'name': 'product_read', 'description': 'Read products', 'resource_type_id': 2, 'action': 'read',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 8, 'name': 'product_update', 'description': 'Update products', 'resource_type_id': 2, 'action': 'update',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 9, 'name': 'product_delete', 'description': 'Delete products', 'resource_type_id': 2, 'action': 'delete',
         'created_at': current_time, 'updated_at': current_time},

        # Orders (resource_type_id=3)
        {'id': 10, 'name': 'order_create', 'description': 'Create orders', 'resource_type_id': 3, 'action': 'create',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 11, 'name': 'order_read', 'description': 'Read orders', 'resource_type_id': 3, 'action': 'read',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 12, 'name': 'order_update', 'description': 'Update orders', 'resource_type_id': 3, 'action': 'update',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 13, 'name': 'order_delete', 'description': 'Delete orders', 'resource_type_id': 3, 'action': 'delete',
         'created_at': current_time, 'updated_at': current_time},

        # Categories (resource_type_id=4)
        {'id': 14, 'name': 'category_create', 'description': 'Create categories', 'resource_type_id': 4,
         'action': 'create', 'created_at': current_time, 'updated_at': current_time},
        {'id': 15, 'name': 'category_read', 'description': 'Read categories', 'resource_type_id': 4, 'action': 'read',
         'created_at': current_time, 'updated_at': current_time},
        {'id': 16, 'name': 'category_update', 'description': 'Update categories', 'resource_type_id': 4,
         'action': 'update', 'created_at': current_time, 'updated_at': current_time},
        {'id': 17, 'name': 'category_delete', 'description': 'Delete categories', 'resource_type_id': 4,
         'action': 'delete', 'created_at': current_time, 'updated_at': current_time},
    ])

    op.bulk_insert(role_permissions_table, [
        # Admin - все права
        *[{'role_id': 1, 'permission_id': i, 'created_at': current_time, 'updated_at': current_time} for i in
          range(1, 18)],

        # Manager - управление продуктами и заказами
        {'role_id': 2, 'permission_id': 6, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 7, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 8, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 9, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 10, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 11, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 12, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 13, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 2, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 2, 'permission_id': 15, 'created_at': current_time, 'updated_at': current_time},

        # User - базовые права
        {'role_id': 3, 'permission_id': 7, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 3, 'permission_id': 10, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 3, 'permission_id': 11, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 3, 'permission_id': 2, 'created_at': current_time, 'updated_at': current_time},
        {'role_id': 3, 'permission_id': 15, 'created_at': current_time, 'updated_at': current_time},
    ])

    from src.core import security
    password_hasher = security.PasswordHasher(["argon2"])
    hashed_password = password_hasher.hash_password("Qwerty!234")

    op.bulk_insert(users, [
        {
            'id': 1,
            'name': 'Admin User',
            'email': 'admin@example.com',
            'hashed_password': hashed_password,
            'is_active': True,
            'role_id': 1,
            'created_at': current_time,
            'updated_at': current_time
        },
        {
            'id': 2,
            'name': 'Manager User',
            'email': 'manager@example.com',
            'hashed_password': hashed_password,
            'is_active': True,
            'role_id': 2,
            'created_at': current_time,
            'updated_at': current_time
        },
        {
            'id': 3,
            'name': 'Regular User',
            'email': 'user@example.com',
            'hashed_password': hashed_password,
            'is_active': True,
            'role_id': 3,
            'created_at': current_time,
            'updated_at': current_time
        },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM user_permissions")
    op.execute("DELETE FROM refresh_tokens")
    op.execute("DELETE FROM user_sessions")
    op.execute("DELETE FROM users")
    op.execute("DELETE FROM role_permissions")
    op.execute("DELETE FROM permissions")
    op.execute("DELETE FROM user_roles")
    op.execute("DELETE FROM resource_types")
    # ### end Alembic commands ###
