class AuthenticationError(Exception): ...


class InsufficientPermissions(Exception): ...


class UserSessionNotFound(Exception): ...


class TokenNotFound(Exception): ...


class PermissionNotFound(Exception): ...
